# Generated by Django 4.1.5 on 2025-02-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_customer_is_active_remove_customer_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
    ]
